version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/comments'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/event-bus'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/moderation'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/posts'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/query'
    schedule:
      interval: 'weekly'
